status-im/nim-ssz-serialization

- ssz_serialization/merkleization.nim
This makes the merkleization code more consistent regarding identifier
naming, and avoids the dot-syntax for merkleizer function calls.
Furthermore, `hashTreeRootList` is embedded into `hashTreeRootAux`.
Finally, this cleans up some minor syntactic inconsistencies such as
ordering or presence of call brackets.
> Cosmetic updates to merkleizer

- ssz_serialization.nim
This avoids a very verbose case of `XDeclaredButNotUsed` warning during
compile when not using `-d:serialization_tracing=1`.
> Avoid `XDeclaredButNotUsed` warning

- ssz_serialization/merkleization.nim
- ssz_serialization/proofs.nim
- tests/test_all.nim
- tests/test_proofs.nim
This moves generic merkle proof related code from `nimbus-eth2`,
notably enabling use of `is_valid_merkle_branch` by `nimbus-eth1`.
> Integrate merkle proof code from `nimbus-eth2`

- ssz_serialization/codec.nim
Only raising the proper error, which is the same effect it gave with the template like it was before https://github.com/status-im/nim-ssz-serialization/pull/24
Honestly, I find the whole use of the `raisesssz` pragma rather counter productive. It "hides" a bit the actual errors from the user (and user would not have access to this pragma). And it also allows for laziness, in the sense that one just repeats the `raisesssz` instead of the actual errors, which seems to happen. At which point one could question why there are even these different errors and not just one `SszError`. `SszSizeMismatchError` is also not used much at all, and not even for `raiseIncorrectSize()`.
> Set raises to specific error in reallyRaiseMalformedSszError

- ssz_serialization/bitseqs.nim
This adds an assertion that `BitSeq.init` is properly called before
trying to use it in a words enumeration.
> Improve diagnostics when `BitSeq.init` not called

- ssz_serialization/types.nim
- tests/test_ssz_serialization.nim
Having `[]` invalidate the cache is convenient, but comes at a
(significant) performance cost as it gets called even for non-mutable
access due to mutability leaks in the language
*`mitem` like `mitems`
> rename mutable `[]` to `mitem`

- ssz_serialization/merkleization.nim
- ssz_serialization/proofs.nim
- ssz_serialization/types.nim
- tests/test_all.nim
- tests/test_merkleization_types.nim
- tests/test_proofs.nim
This adds functionality for building merkle multiproofs in the same form
that the Ethereum consensus specs suggest, i.e., in descending order of
helper indices. Merkle multiproofs are useful for the light client sync.
https://github.com/ethereum/consensus-specs/blob/v1.1.6/ssz/merkle-proofs.md#merkle-multiproofs
> Add support for building merkle multiproofs

- ssz_serialization/proofs.nim
- ssz_serialization/types.nim
To support adressing any nimbus-eth2 `BeaconState` member, 32-bit wide
indices are not enough. `BeaconState` requires 5 levels of depth;
`VALIDATOR_REGISTRY_LIMIT` for the `validators` array requires 40 levels
for the contents plus 2 levels for `len` and the root. Another 4 levels
are required for `Validator`. This means that 52-bit indices are needed.
Extending to `uint64` should provide enough leeway without requiring
further implementation adjustments.
> Use `uint64` for `GeneralizedIndex`

- ssz_serialization/merkleization.nim
Some of the computation resulted in large uint64 values being casted to
int64, leading to problems in Nim 1.6. Made the logic more defensive to
avoid these casts.
> avoid casting unsigned to signed for nim 1.6

- ssz_serialization/merkleization.nim
Correct capitalization of a `noinit` keyword to pass stylecheck.
> fix 'noInit' should be: 'noinit'

- ssz_serialization.nim
- ssz_serialization/bitseqs.nim
- ssz_serialization/codec.nim
- ssz_serialization/dynamic_navigator.nim
- ssz_serialization/merkleization.nim
- ssz_serialization/navigator.nim
- ssz_serialization/proofs.nim
- ssz_serialization/types.nim
A continuation of https://github.com/status-im/nimbus-eth2/pull/3888
Rationale (from that link):
> Currently (the latest commit in unstable branch), the CI log for the 1.6 branch has **107.000 lines**.
Removing every hint about cannot raise 'Defect' (including the ones in the vendor directory) leaves **16.000 lines**. 85% off.
> make it more Nim 1.4+ compatible

- .github/workflows/ci.yml
- ssz_serialization.nim
- ssz_serialization/codec.nim
- ssz_serialization/merkleization.nim
- ssz_serialization/types.nim
- tests/test_all.nim
- tests/test_ssz_optional.nim
Adds support for SSZ optionals according to EIP-6475. https://eips.ethereum.org/EIPS/eip-6475
> implement SSZ Optionals (EIP-6475)

- .github/workflows/ci.yml
- ssz_serialization.nim
- ssz_serialization/codec.nim
- tests/test_ssz_optional.nim
EIP-6475 was bumped to emit an additional `0x01` byte in the `Some` case of optionals to allow nesting `Optional` and `Optional[List]` and to provide compatibility with `Union` serialization. Note that the `None` case is still serialized as empty.
https://eips.ethereum.org/EIPS/eip-6475
https://github.com/ethereum/EIPs/pull/6945
> update for latest `Optional` spec

- ssz_serialization.nim
The type `SszMaxSizeExceeded` is unused and can be removed.
> rm unused `SszMaxSizeExceeded`

- ssz_serialization/codec.nim
- ssz_serialization/merkleization.nim
- tests/test_merkleization.nim
* use 64-byte buffer to pass a full sha256 block at a time to `digest`, thus avoiding internal buffer copies
* avoid several unnecessary `zeroMem` calls via {.noinit.} / etc
* process blobs 64 bytes at a time instead of splitting into 32-byte chunks
Merkle proof generation could be sped up the same way.
HTR of recent state - pre:
```
[arnetheduck@praeceps ncli]$ time ./ncli hashTreeRoot capella_state
./state.20230609.ssz
51f87eb876461ba7f3fea40e0c248b3de6db7c035501b3ec71f8449185fc0ac8
real	0m1.056s
user	0m0.942s
sys	0m0.111s
```
post:
```
[arnetheduck@praeceps ncli]$ time ./ncli hashTreeRoot capella_state
./state.20230609.ssz
51f87eb876461ba7f3fea40e0c248b3de6db7c035501b3ec71f8449185fc0ac8
real	0m0.832s
user	0m0.726s
sys	0m0.104s
```
Needs https://github.com/status-im/nim-stew/pull/193
> avoid copies - 20% hash_tree_root speedup

- ssz_serialization.nim
- ssz_serialization/codec.nim
- ssz_serialization/types.nim
When loading SSZ from disk, we can bulk-memcpy trivial types that match the SSZ serialization exactly (ie `array[Digest]`) - this saves a few ms when loading large SSZ objects like beacon states.
Also avoid zero:ing seqs on load - unfortunately, this works only for numbers).
> bulk-copy simple types

- ssz_serialization.nim
- ssz_serialization/codec.nim
The `SingleMemberUnion` is a never-used vestige of https://github.com/status-im/nimbus-eth2/pull/2858 which tentatively [defined a `Transaction` as an SSZ `Union`](https://github.com/ethereum/consensus-specs/blob/v1.1.3/specs/merge/beacon-chain.md#custom-types) briefly.
The 1.1.4 spec [switches it to the `ByteList`](https://github.com/ethereum/consensus-specs/blob/v1.1.4/specs/merge/beacon-chain.md#custom-types) it remains.
The idea of something like a `SingleMemberUnion` didn't entirely fade, but a more current representation is [implemented already](https://github.com/status-im/nim-ssz-serialization/pull/41), so at this point `SingleMemberUnion` itself should be removed.
> remove SingleMemberUnion read/write support

- ssz_serialization.nim
- ssz_serialization/types.nim
Remove unnecessary `{.raises: [SerializationError].}` from `writeValue`. `SerializationError` can only occur while reading.
> remove spurious `{.raises.}`

- ssz_serialization/merkleization.nim
- tests/test_all.nim
- tests/test_hash_tree_root.nim
fix #64
only need to add one mixin.
> Fix hash_tree_root cannot compile with nim 1.6.12

- ssz_serialization/types.nim
Nim has improved slightly since 2019: https://github.com/status-im/nimbus-eth2/pull/335 where this workaround was introduced
Reduces memory allocations.
> convert func to iterator

- ssz_serialization/types.nim
When bumping to latest nim-ssz-serialization in nimbus-eth1, this const is giving issues:
```
Building: build/fluffy
/Users/deme/repos/nimbus-eth1/vendor/nim-ssz-serialization/ssz_serialization/types.nim(294, 35) Error: type mismatch: got 'array[0..31, int]' for '[0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
1, 1, 1, 1, 1, 1]' but expected 'array[0..31, byte]'
```
> Fix compiler complaining type mismatch for byte array

- ssz_serialization/merkleization.nim
In Nim 2.0, getting
```
Error: type mismatch
Expression: `[]`(x, 0 + i`gensym1615)
[1] x: array[0..63, Eth2Digest]
[2] 0 + i`gensym1615: int
```
if `chunkedHashTreeRoot[T: not BasicType]` is a `template`. Aligning it to `func`, same as done for the `chunkedHashTreeRoot[T: BasicType`, fixes this.
> workaround for Nim 2.0 issue with the template

- ssz_serialization.nim
- ssz_serialization/codec.nim
- ssz_serialization/dynamic_navigator.nim
- ssz_serialization/navigator.nim
With the current `[MalformedSszError, SszSizeMismatchError]` definition for `{.pragma: raisesssz.}`, a lot of `XCannotRaiseY` are sometimes generated when a concrete implementation does not actually raise all of the potential errors. Declaring `{.pragma: raisessz.}` to raise common `[SszError]` instead has the same semantics but reduces spurious hints.
> use common super-type in `raisesssz` pragma

- ssz_serialization/merkleization.nim
- tests/test_hash_tree_root.nim
This PR removes the remaining significant temporaries, zeroMems and copies in the implemenation and improves general code safety by removing some of the pointer tricks used.
Although this introduces some code bloat due to parts of the implementation ending up being more generic, this also opens up tracking limits and fixing a number of issues involving writing past it.
> simplify implementation, more zeroMem fixes

- ssz_serialization/codec.nim
- tests/test_ssz_union.nim
This removes a check that was (probably) there to verify if the input data had more than just the selector byte so that it wouldn't indicate a `None`. However, there is  also the case of an empty SSZ.List that encoded as 0 bytes.
This does sound a bit strange as the potential None value in an SSZ Union also has 0 bytes, but both cases can be decoded properly as a None is defined by having no field (which is checked at compile time).
> Fix error on decoding of an empty list in an SSZ Union

- ssz_serialization/merkleization.nim
More closely matches implementation and avoids generic bloat.
Renamed to avoid accidental limit-vs-height confusion.
> Use tree height instead of chunk limit for merkleizer

- ssz_serialization/navigator.nim
`RangeError` got deprecated in favor of `RangeDefect`. Update comment.
> rename reference of `RangeError` to `RangeDefect`

- ssz_serialization/codec.nim
- ssz_serialization/merkleization.nim
- ssz_serialization/types.nim
This PR allows writing a custom hash_tree_root function even though the type has a `toSszBytes` function
> allow customizing htr for type

- ssz_serialization.nim
- ssz_serialization/codec.nim
Lists of distincts require use of `toSszType` to properly decode.
> use `toSszType` for elements of `HashList|HashArray|List|array`

- ssz_serialization.nim
- ssz_serialization/codec.nim
- ssz_serialization/dynamic_navigator.nim
- ssz_serialization/merkleization.nim
- ssz_serialization/navigator.nim
- ssz_serialization/types.nim
- tests/test_ssz_serialization.nim
Applying `toSszType` in more places allows simple case `distinct uint64` to work properly. Complex scenarios where the `toSszType` helper returns a `BasicType` of different size than original are still unsupported.
> more fixes for `distinct` integer types

- ssz_serialization.nimble
Fixes a regression from #69 that results in `--mm:refc` tests running twice. `run` already tests with both `--mm:orc` and `--mm:refc`.
> avoid double testing `--mm:refc`

- ssz_serialization.nim
- tests/test_ssz_serialization.nim
Because it will trigger `dereferencing pointer to incomplete type` error on linux gcc.
> Restrict toSszType usage to non SszType in readSszBytes

- .github/workflows/ci.yml
- ssz_serialization.nim
- ssz_serialization.nimble
- ssz_serialization/codec.nim
- ssz_serialization/merkleization.nim
- ssz_serialization/proofs.nim
- ssz_serialization/types.nim
This is a milder version of https://github.com/status-im/nim-ssz-serialization/pull/89 — it keeps Nim 1.6 support.
> update ci.yml and fix deprecations

- ssz_serialization/types.nim
The `ByteList` is one that we use a lot in Portal.
> Add two convenience aliases from specification

- ssz_serialization/types.nim
- tests/test_merkleization.nim
`declval` is only supposed to be used in a `type`/`typeof`-ish expression. It was not here, but through Nim 2.0.8 that had been allowed. Nim 2.0.10 notices this and properly responds `false` to that `compiles(...)` otherwise.
> fix distinct BasicType compressed detection in dataPerChunk

- ssz_serialization.nimble
Addresses
- https://github.com/nim-lang/Nim/issues/23445
> require Nim 2.0

- ssz_serialization/types.nim
- tests/test_ssz_serialization.nim
Introduces `minSize` as a counterpart to `maxSize` (#20).
> Add `minSize` helper

- ssz_serialization/merkleization.nim
- ssz_serialization/types.nim
- tests/test_merkleization_types.nim
The caches for HashArray|HashList assume a tree size that's a multiple of 2 chunks, which doesn't work when there is only a single chunk. Ensure that the single chunk case also works.
> Fix IndexDefect when hashing HashArray|HashList with <= 32byte capacity

- ssz_serialization/types.nim
- tests/test_proofs.nim
- Warning: Use `newSeqUninit` instead; newSeqUninitialized is deprecated
- Warning: imported and not used: 'byteutils'
> fix compiler warnings

- config.nims
- ssz_serialization/codec.nim
- tests/test_ssz_serialization.nim
Otherwise, overloading works only for the top-level call which is surprising.
> `readSszBytes` overload should be used for nested objects also

- ssz_serialization/digest.nim
- https://github.com/OffchainLabs/hashtree/pull/42
- https://github.com/OffchainLabs/hashtree/pull/43
This version of `hashtree` contains its own C fallback, so don't need the local one in `nim-ssz-serialization`.
> bump hashtree to not need CPU-agnostic fallback
